name: any-pr

on: [pull_request]

jobs:
  build_test:
    name: Build test
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        node-version: [11.x]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile
      - run: yarn build:release
      - run: yarn test
  build_test_wasm_env_interop:
    name: Build and Test WASM running cross OS and NodeJS versions
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        node-version: [11.x, 12.x, 13.x, 14.x, 15.x, 16.x]
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile
      - run: yarn build:release
      - run: yarn test:wasm
  build_test_native_node_env_interop:
    name: Build and Test native module running cross OS and NodeJS versions
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        node-version: [11.x, 12.x, 13.x, 14.x, 15.x, 16.x]
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile
      - run: yarn build:release
      - run: yarn test:node
